[package]
name = "awatistic"
version = "1.0.0"
edition = "2021"
authors = [ "Neon." ]
description = "Awatistic AWA5.0 interpreter"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
